name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Ramesh K P"
      - name: Multiline Command
        run: |
          python -V
          pip -V


